### ISSUE TITLE
Menu links should be relative (I think)

### ISSUE THREAD

**Issue by MichalYoung** [tcolb/uo-makers-club#1]
When I cloned to http://ix.cs.uoregon.edu/~michal/makers/ for testing, I found the links in the menu didn't work.  Looking at the code in the include directory, the header, I see that they are links to absolute URLs (starting with / ), e.g., /index.  If the pages don't live at the top-level of the overall site , then these will break with 404.  

If maker club gets its own domain, then that is not an issue.  It depends on how the site is deployed.

**Comment by tcolb** [comment]
Should work now If I'm understanding correctly, changed nav links to
`<a class="nav-link" href="./filename.php">Filename</a>`

**Comment by MichalYoung** [comment]
Yes, working now for me.   I think the ./page.php scheme will be fine as long as the site is "flat".  If it grows enough to require subdirectories, then it will become necessary to write a little bit of PHP to determine the root of the site, so that PHP can fill in the right relative links regardless of page location, but there is no need for that now.   I've done this before for class sites and can provide example code. (Or maybe there is a better way to do it.) 

There are a couple of broken links in the 'future projects' section, but that's a separate issue and not critical.   I'll file a separate issue for that.
